
           <!-- <input type="text" id="insert0" placeholder="Qui il primo numero">
            <input type="text" id="insert1" placeholder="Qui il secondo numero numero"><br>
            
            --> 
            <div id="display">
            <div id="result"></div>result:
            <div id="insert1"></div>
           
            <div id="operando"></div>
            
            <div id="insert0"></div>
            </div>
             
            <div id="box">
            <!--button class="cmd" id="cancAl"><--</button-->
            <button class="cmd" id="cancAl">C</button>
            <button class="cmd" id="canc">CE</button>
            <button class="aloneOper" id="inv">±</button>
            <button class="aloneOper" id="sqrt">√</button>
            <br>                
            <button class="numb" value="7" >7</button>
            <button class="numb" value="8">8</button>
            <button class="numb" value="9">9</button>
            <button class="oper" id="div">/</button>
            <button class="aloneOper" id="perc">%</button>
            <br>
            <button class="numb" value="4">4</button>
            <button class="numb" value="5">5</button>
            <button class="numb" value="6">6</button>
            <button class="oper" id="mul">*</button>
            <button class="aloneOper" id="reciproc">1/x</button>
            <br>
            <button class="numb" value="1" >1</button>
            <button class="numb" value="2">2</button>
            <button class="numb" value="3">3</button>
            <button class="oper" id="sub">-</button>
            <br>
            <button class="numb" value="0" id="zero">0</button>
            <button class="numb" value=".">,</button>
            <button class="oper" id="sum">+</button>
            <button id="submit">=</button><br>
            
            
            </div>
</div>

